# Generated by Django 2.1.7 on 2019-02-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images_backend', '0002_auto_20190217_1555'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstanceValues',
            new_name='InstanceValue',
        ),
    ]
