# Generated by Django 2.1.7 on 2019-02-17 18:14

from django.db import migrations, models
import images_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('images_backend', '0004_auto_20190217_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodelclass',
            name='uuid',
            field=models.CharField(default=images_backend.models.uuid_without_hypens, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
