# Generated by Django 2.1.7 on 2019-02-17 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('images_backend', '0005_auto_20190217_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDictionary',
            fields=[
                ('basemodelclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='images_backend.BaseModelClass')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images_backend.AttributeDefinition')),
            ],
            bases=('images_backend.basemodelclass',),
        ),
        migrations.RemoveField(
            model_name='instancevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='instancevalue',
            name='instance',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryDefinition',
        ),
        migrations.AddField(
            model_name='categorydictionary',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images_backend.CategoryDefinition'),
        ),
    ]
