# Generated by Django 2.1.3 on 2019-02-21 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images_backend', '0007_auto_20190220_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancevalue',
            name='image_source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='images_backend.Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attributedefinition',
            name='value_type',
            field=models.CharField(choices=[('S', 'String'), ('B', 'Boolean'), ('I', 'Integer'), ('D', 'Double')], default='S', max_length=1),
        ),
    ]
